config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :uploaders do
    member do
      delete :delete_file
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "uploaders#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/uploader.rb
class Uploader < ApplicationRecord
  has_many_attached :files
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/uploaders_controller.rb
class UploadersController < ApplicationController
  before_action :set_uploader, only: %i[ show edit update destroy ]

  # GET /uploaders or /uploaders.json
  def index
    @uploaders = Uploader.where(user: current_user)
  end

  # GET /uploaders/1 or /uploaders/1.json
  def show
    redirect_to root_path unless @uploader
  end

  # GET /uploaders/new
  def new
    @uploader = Uploader.new
  end

  # GET /uploaders/1/edit
  def edit
  end

  # POST /uploaders or /uploaders.json
  def create
    @uploader = Uploader.new(uploader_params)

    respond_to do |format|
      if @uploader.save
        format.html { redirect_to uploader_url(@uploader), notice: "Uploader was successfully created." }
        format.json { render :show, status: :created, location: @uploader }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @uploader.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uploaders/1 or /uploaders/1.json
  def update
    respond_to do |format|
      if @uploader.update(uploader_params)
        format.html { redirect_to uploader_url(@uploader), notice: "Uploader was successfully updated." }
        format.json { render :show, status: :ok, location: @uploader }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @uploader.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploaders/1 or /uploaders/1.json
  def destroy
    @uploader.destroy

    respond_to do |format|
      format.html { redirect_to uploaders_url, notice: "Uploader was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def delete_file
    file = ActiveStorage::Attachment.find(params[:id])
    file.purge
    redirect_back(fallback_location: root_path)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_uploader
    @uploader = Uploader.find_by(id: params[:id])
  end

  # Only allow a list of trusted parameters through.
  def uploader_params
    params.require(:uploader).permit(:title, :description, :user_id, files: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploaders_helper.rb
module UploadersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileUpload</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <p class="navbar-text float-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete%>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </p>
    <%= yield %>
  </body>
</html>

app/views/uploaders/_form.html.erb
<%= form_with(model: uploader) do |form| %>
  <% if uploader.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(uploader.errors.count, "error") %> prohibited this uploader from being saved:</h2>

      <ul>
        <% uploader.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :files %>
    <%= form.file_field :files, multiple: true %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/uploaders/_uploader.html.erb
<div id="<%= dom_id uploader %>">
  <p>
    <strong>Title:</strong>
    <%= uploader.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= uploader.description %>
  </p>

</div>

app/views/uploaders/edit.html.erb
<h1>Editing uploader</h1>

<%= render "form", uploader: @uploader %>

<br>

<div>
  <%= link_to "Show this uploader", @uploader %> |
  <%= link_to "Back to uploaders", uploaders_path %>
</div>

app/views/uploaders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Uploaders</h1>

<div id="uploaders">
  <% @uploaders.each do |uploader| %>
    <%= render uploader %>
    <% uploader.files.each do |file| %>
      <%= link_to file.filename, rails_blob_path(file, disposition: :inline) %>
    <% end %>

    <p>
      <%= link_to "Show this uploader", uploader %>
    </p>
  <% end %>
</div>

<%= link_to "New uploader", new_uploader_path %>

app/views/uploaders/new.html.erb
<h1>New uploader</h1>

<%= render "form", uploader: @uploader %>

<br>

<div>
  <%= link_to "Back to uploaders", uploaders_path %>
</div>

app/views/uploaders/show.html.erb
<%= render @uploader %>
<% files = @uploader.files %>
<% if files.any? %>
  Attachments:
  <% files.each do |file| %>
    <%= link_to file.filename, rails_blob_path(file, disposition: :inline) %>
    <div><strong>Link to share:</strong><%= rails_blob_url(file, disposition: :inline, expires_in: 50.seconds) %></div>
    <p>#TODO: *This URL will be replaced with slug.</p>
    <%= button_to 'Remove', delete_file_uploader_path(file.id), method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
<% end %>

<div>
  <%= link_to "Edit this uploader", edit_uploader_path(@uploader) %> |
  <%= link_to "Back to uploaders", uploaders_path %>

  <%= link_to "Destroy this uploader", @uploader, 'data-turbo-method': :delete %>
</div>